#!/usr/bin/with-contenv bash

# Current Transcoder location
FILENAME="/usr/lib/plexmediaserver/Plex Transcoder"
# Size to distinguish between patch and Transcoder
MAXSIZE=200000
# Get size of file
FILESIZE=$(stat -c%s "$FILENAME")

if (( FILESIZE < MAXSIZE )); then
  echo "Plex Transcoder is already patched for NVDEC-support, aborting patch."
else
  mv /usr/lib/plexmediaserver/Plex\ Transcoder /usr/lib/plexmediaserver/Plex\ Transcoder2
  cp /etc/plex-nvdec-patch/transcoder-nvdec-patch.sh /usr/lib/plexmediaserver/Plex\ Transcoder
  chmod 755 /usr/lib/plexmediaserver/Plex\ Transcoder
  chmod u+x /usr/lib/plexmediaserver/Plex\ Transcoder
fi
